version: '3.4'

services:

  server:
    image: go-mongo-api
    container_name: "go-mongo-api"
    build: ./
    command: ./app
    ports:
      - 80:80
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_DATABASE=testdb
    volumes:
      - ./.data/db:/data/db
    ports:
      - 27027:27017
    command: mongod --logpath=/dev/null # --quiet