// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";
import "./requests/Create.js";
import "./requests/Login.js";
import "./requests/Get-all-Bookmarks.js";
import "./requests/Create-Bookmark.js";
import "./requests/Update-Bookmark.js";
import "./requests/Get-Bookmark.js";
import "./requests/Delete-Bookmark.js";

export let options = { maxRedirects: 4, iterations: "1" };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options,
  collection: {
    url: "https://webapp-gomongo.azurewebsites.net",
    token: "",
    bookmark: "64a7cc1ec68cd4acdee1be1a",
    username: "{{$randomUserName}}",
    password: "{{$randomPassword}}",
    userid: ""
  }
});

export default function() {
  postman[Request]("Create");
  postman[Request]("Login");
  postman[Request]("Get all Bookmarks");
  postman[Request]("Create Bookmark");
  postman[Request]("Update Bookmark");
  postman[Request]("Get Bookmark");
  postman[Request]("Delete Bookmark");
}
