port: 80

auth:
  hash_salt: "some-hash"
  signing_key: "some-signing-key"
  token_ttl: 86400

mongo:
  # uri: "mongodb://mongodb:27027"
  # uri: "mongodb://localhost:27027"
  # uri: "mongodb://host.docker.internal:27027"
  uri: mongodb+srv://user:4Nu0Bz3F633hgZUX@cluster0.fqzualv.mongodb.net/
  name: "testdb"
  user_collection: "users"
  bookmark_collection: "bookmarks"